---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./homechart/ks.yaml
  # - ./donetick/ks.yaml
  - ./immich/ks.yaml
  - ./n8n/ks.yaml
  # - ./homarr/ks.yaml
  - ./glance/ks.yaml
  # - ./trilium/ks.yaml
  - ./obsidian-sync/ks.yaml
  - ./vikunja/ks.yaml
