---
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: obsidian-sync
spec:
  name: Obsidian Sync
  icon: https://obsidian.md/favicon.ico
  url: &url https://obsidian-sync.${ROOT_DOMAIN}
  description: Self-hosted Obsidian LiveSync server using CouchDB
  category: Applications
  access_policy:
    groups:
      - family
      - friends

  authentik:
    proxy:
      mode: "forward_single"
      externalHost: *url

  gatus:
    - name: Obsidian Sync
      url: https://obsidian-sync.${ROOT_DOMAIN}/_up
      interval: 1m
      conditions:
        - "[STATUS] == 200"
        - "[RESPONSE_TIME] < 1000"
