---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obsidian-sync
resources:
  - ./configmap.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./middleware.yaml
  - ./post-install-hook.yaml
  - ./definition.yaml
