---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Retrom
  category: &category Games
  description: Retrom is a game library management and streaming server
  url: &url https://${APP}.${ROOT_DOMAIN}
  icon: https://raw.githubusercontent.com/JMBeresford/retrom/refs/heads/main/packages/client/src-tauri/icons/128x128.png
  access_policy:
    groups:
      - friends
      - family
  authentik:
    oauth2:
      clientType: confidential
      allowedRedirectUris:
        - url: "https://${APP}.${ROOT_DOMAIN}/auth/callback"
      propertyMappings:
        - email
        - openid
        - profile
      includeClaimsInIdToken: true
      subMode: user_email
  gatus:
    - group: Applications
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
