---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-env
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        CLIENT_IGDB_CLIENT_ID: "{{ .twitch_username }}"
        CLIENT_IGDB_CLIENT_SECRET: "{{ .twitch_credential }}"
        CLIENT_STEAM_API_KEY: "{{ .steam_credential }}"
        DB_HOST: "{{ .postgres_hostname }}"
        DB_PORT: "{{ .postgres_port }}"
        DB_USER: "{{ .postgres_username }}"
        DB_PASSWORD: "{{ .postgres_password }}"
        DB_NAME: "{{ .postgres_database }}"
        OIDC_ENABLED: "true"
        OIDC_ISSUER_URL: "{{ .oidc_issuer }}"
        OIDC_CLIENT_ID: "{{ .oidc_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        OIDC_REDIRECT_URI: "https://${APP}.${ROOT_DOMAIN}/auth/callback"

  dataFrom:
    - extract:
        key: 'Twitch Developer'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "twitch_$1"
    - extract:
        key: 'Steam API'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "steam_$1"
    - extract:
        key: '${CLUSTER_CNAME}-${APP}-oidc-credentials'
      rewrite:
        - regexp:
            source: "(.*)"
            target: "oidc_$1"
    - extract:
        key: '${APP}-postgres'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
