---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/upgrade.cattle.io/plan_v1.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: kubernetes
spec:
  version: "${KUBERNETES_VERSION}"
  concurrency: 1
  exclusive: true
  serviceAccountName: system-upgrade-controller
  secrets:
    - name: system-upgrade-controller
      path: /var/run/secrets/talos.dev
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  upgrade:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    image: "ghcr.io/siderolabs/talosctl:v1.11.6@sha256:9f7d71e27190f19f04cbd5ad59752af75e54920c4601072cef93a578097be1b9"
    envs:
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    args:
      - --nodes=$(NODE_IP)
      - upgrade-k8s
      - --to=$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)
