---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "sgc-thanos-write.${TAILSCALE_DOMAIN}"
    tailscale.com/proxy-group: egress
  name: ${APP}-thanos
spec:
  externalName: unused
  type: ExternalName
  ports:
    - port: 10901
      name: grpc
