---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/service.json
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "thanos-write-svc.${TAILSCALE_DOMAIN}"
  name: thanos-write-svc
spec:
  externalName: unused
  type: ExternalName
  ports:
    - port: 10901
      targetPort: 10901
      name: http
    - port: 10902
      targetPort: 10902
      name: grpc
    - port: 19291
      targetPort: 19291
      name: remote
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/service.json
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "alertmanager-svc.${TAILSCALE_DOMAIN}"
  name: alertmanager-svc
spec:
  externalName: unused
  type: ExternalName
  ports:
    - port: 9093
      targetPort: 9093
      name: http
