---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "thanos-write.${TAILSCALE_DOMAIN}"
    tailscale.com/proxy-group: egress
  name: thanos-write
spec:
  externalName: unused
  type: ExternalName
  ports:
    - port: 10901
      targetPort: 10901
      name: grpc
    - port: 10902
      targetPort: 10902
      name: http
