
kind: HelmRelease
metadata:
  name: patch
spec:
  valuesFrom:

    - kind: Secret
      name: &name littles-tech-github-app
      targetPath: githubConfigUrl
      valuesKey: githubConfigUrl

    - kind: Secret
      name: *name
      targetPath: githubConfigSecret.github_app_id
      valuesKey: github_app_id

    - kind: Secret
      name: *name
      targetPath: githubConfigSecret.github_app_installation_id
      valuesKey: github_app_installation_id

    - kind: Secret
      name: *name
      targetPath: githubConfigSecret.github_app_private_key
      valuesKey: github_app_private_key

    - kind: Secret
      name: *name
      targetPath: controllerServiceAccount.name
      valuesKey: controllerServiceAccountName

    - kind: Secret
      name: *name
      targetPath: controllerServiceAccount.namespace
      valuesKey: controllerServiceAccountNamespace
