---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-env
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        ALLOWED_HOSTS: recipes.${ROOT_DOMAIN}
        COMMENT_PREF_DEFAULT: "1"
        DEBUG: "0"
        DEFAULT_FROM_EMAIL: recipes@${ROOT_DOMAIN}
        # EMAIL_HOST: smtp-relay.networking.svc.cluster.local
        # EMAIL_PORT: 2525
        ENABLE_PDF_EXPORT: "1"
        ENABLE_SIGNUP: "0"
        FRACTION_PREF_DEFAULT: "0"
        GUNICORN_MEDIA: "0"
        SHOPPING_MIN_AUTOSYNC_INTERVAL: "5"
        SOCIAL_PROVIDERS: allauth.socialaccount.providers.openid_connect
        TZ: "${TIMEZONE}"
        SECRET_KEY: "{{ .secret_password }}"
        DB_ENGINE: django.db.backends.postgresql
        POSTGRES_HOST: "{{ .postgres_hostname }}"
        POSTGRES_PORT: "{{ .postgres_port }}"
        POSTGRES_DB: "{{ .postgres_database }}"
        POSTGRES_USER: "{{ .postgres_username }}"
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
        REMOTE_USER_AUTH: "1"
  dataFrom:
    - extract:
        key: 'Tandoor Secret Key'
      rewrite:
        - regexp:
            source: "(.*)"
            target: "secret_$1"
    - extract:
        key: '${APP}-postgres'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
