---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: autobrr
  category: Media Management
  description: Modern download automation tool for torrents and usenet
  url: &url https://${APP}.${ROOT_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/autobrr.svg
  access_policy:
    groups:
      - media-managers
  authentik:
    oauth2:
      clientType: confidential
      allowedRedirectUris:
      - url: https://${APP}.${ROOT_DOMAIN}/api/auth/oidc/callback
      propertyMappings:
        - email
        - openid
        - profile
      subMode: user_email
      includeClaimsInIdToken: true
  gatus:
    - group: "Applications"
      url: https://${APP}.${ROOT_DOMAIN}/api/healthz/liveness
      method: GET
      conditions:
        - "[STATUS] == 200"
