---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-oidc
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-oidc
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        AUTOBRR__OIDC_ENABLED: "true"
        AUTOBRR__OIDC_ISSUER: "{{ .oidc_issuer }}"
        AUTOBRR__OIDC_CLIENT_ID: "{{ .oidc_client_id }}"
        AUTOBRR__OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        AUTOBRR__OIDC_REDIRECT_URL: "https://${APP}.${ROOT_DOMAIN}/api/auth/oidc/callback"
        AUTOBRR__OIDC_DISABLE_BUILT_IN_LOGIN: "true"
  dataFrom:
    - extract:
        key: '${CLUSTER_CNAME}-${APP}-oidc-credentials'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "oidc_$1"
