---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dispatcharr-addons
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  interval: 1h
  timeout: 10m
  install:
    createNamespace: true
    replace: true
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: -1
      strategy: rollback
  rollback:
    force: true
    cleanupOnFail: true
    recreate: true
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        initContainers:
          chown-dbdir:
            image:
              repository: alpine
              tag: 3.23.2@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62
              pullPolicy: IfNotPresent
            command:
              - /bin/sh
              - -c
            args:
              - |
                chmod 0750 /data/db
            securityContext:
              runAsUser: 0
              fsGroupChangePolicy: OnRootMismatch

        containers:
          ecm:
            image:
              repository: ghcr.io/motwakorb/enhancedchannelmanager
              tag: "0.8.4@sha256:88430fdef231afdd57260ab8843f066683edebd00d398c9121023e25b0ec9272"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &ecm-port 6100
                  initialDelaySeconds: 10
                  periodSeconds: 60
                  timeoutSeconds: 10
                  failureThreshold: 5
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 512Mi
          game-thumbs:
            image:
              repository: ghcr.io/sethwv/game-thumbs
              tag: v1.4.0@sha256:659f43c4922e226cfda3727c93e1a54a2227d3baf2b05a0c33645bb87130a911
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
          teamarr:
            image:
              repository: ghcr.io/pharaoh-labs/teamarr
              tag: "2.0.9@sha256:42feece985425735442dc19d6af2d1cc6007d92fbb0950da2f8d9478035de11f"
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &teamarr-port 9195
                  initialDelaySeconds: 10
                  periodSeconds: 60
                  timeoutSeconds: 10
                  failureThreshold: 5
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 2Gi
          streamwatchdog:
            image:
              repository: sergeantpanda/streamwatchdog
              tag: v2.2.1
            env:
              SERVER_URL: http://dispatcharr-app.equestria.svc.cluster.local:9191
              USERNAME:
                secretKeyRef:
                  name: dispatcharr
                  key: username
              PASSWORD:
                secretKeyRef:
                  name: dispatcharr
                  key: password
              MODULE: Dispatcharr
              ERROR_THRESHOLD: "2"
              TZ: ${TIMEZONE}

    # -- Configures service settings for the chart.
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: intel.feature.node.kubernetes.io/gpu
                operator: In
                values:
                - "true"
    service:
      ecm:
        controller: app
        type: ClusterIP
        ports:
          http:
            port: *ecm-port
      game-thumbs:
        controller: app
        type: ClusterIP
        ports:
          http:
            port: &game-thumbs-port 3000
      teamarr:
        controller: app
        type: ClusterIP
        ports:
          http:
            port: *teamarr-port

    persistence:
      config:
        existingClaim: ${APP}
        advancedMounts:
          app:
            chown-dbdir:
              - path: /data
            ecm:
              - path: /config
                subPath: ecm
            game-thumbs:
              - path: /app/.cache
                subPath: game-thumbs/cache
            teamarr:
              - path: /app/data
                subPath: teamarr
      media:
        existingClaim: truenas-media
      tmpfs:
        type: emptyDir
        globalMounts:
            - path: /tmp

    route:
      ecm:
        parentRefs:
          - name: internal
            namespace: network
            kind: Gateway
        hostnames:
          - "dispatcharr-ecm.${ROOT_DOMAIN}"
        kind: HTTPRoute
        rules:
          - backendRefs:
              - identifier: ecm
                port: *ecm-port
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: local-user
      teamarr:
        parentRefs:
          - name: internal
            namespace: network
            kind: Gateway
        hostnames:
          - "dispatcharr-teamarr.${ROOT_DOMAIN}"
        kind: HTTPRoute
        rules:
          - backendRefs:
              - identifier: teamarr
                port: *teamarr-port
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: local-user

      game-thumbs:
        parentRefs:
          - name: internal
            namespace: network
            kind: Gateway
        hostnames:
          - "dispatcharr-thumbs.${ROOT_DOMAIN}"
        kind: HTTPRoute
        rules:
          - backendRefs:
              - identifier: game-thumbs
                port: *game-thumbs-port
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: local-user
