# yaml-language-server: $schema=https://raw.githubusercontent.com/not-first/glance-schema/master/schema.json#/properties/pages
- name: Stargate Command
  width: wide
  desktop-navigation-width: default


  columns:

    - size: full
      widgets:
        - type: calendar

    - size: full
      widgets:
        - type: calendar


        # glance-k8s Apps (stargate) - via Tailscale cross-cluster access
        - type: extension
          url: https://glance-k8s.sgc.${ROOT_DOMAIN}/extension/apps
          allow-potentially-dangerous-html: true
          cache: 10m
          title: Stargate Apps
          parameters:
            show-if: glance.hide != "true"
          allow-insecure: true
