---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./readarr-ebook/ks.yaml
  - ./readarr-audio/ks.yaml
  - ./openbooks/ks.yaml
  - ./audiobookshelf/ks.yaml
  - ./lazylibrarian/ks.yaml
