---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Collabora Online
  category: Applications
  description: Collabora Online is a powerful online office suite that supports all major document, spreadsheet, and presentation file formats, enabling collaborative editing and real-time communication.
  url: &url https://collabora.${ROOT_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/collabora-online.svg
  access_policy:
    groups:
      - family
      - friends
  authentik:
    proxy:
      mode: "forward_single"
      externalHost: *url
  gatus:
    - group: "Applications"
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
