---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secret.yaml
patches:
  - path: ./patch.yaml
    target:
      kind: HelmRelease
  - target:
      kind: HelmRelease
    patch: |-
      - op: replace
        path: /metadata/name
        value: littles-tech-runners
      - op: replace
        path: /spec/values/fullnameOverride
        value: littles-tech-runners
      - op: replace
        path: /spec/values/runnerScaleSetName
        value: littles-tech-runners
      - op: replace
        path: /spec/values/maxRunners
        value: 4
      - op: replace
        path: /spec/values/minRunners
        value: 1
      - op: add
        path: /spec/values/template/spec/containers/0/resources/limits/memory
        value: "8Gi"
      - op: add
        path: /spec/values/template/spec/containers/0/resources/requests/cpu
        value: "2"
      - op: add
        path: /spec/values/template/spec/containers/0/resources/requests/memory
        value: "3Gi"
