---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: audiobookshelf
spec:
  name: Audiobookshelf
  category: Media Management
  description: Audiobookshelf
  url: &url https://${APP}.${CLUSTER_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/audiobookshelf.svg
  access_policy:
    groups:
      - media-managers
  authentik:
    proxy:
      mode: "forward_single"
      externalHost: *url
  gatus:
    - group: "Applications"
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
