---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bazarr/ks.yaml
  # - ./emby/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
  - ./lidarr/ks.yaml
  - ./mylar/ks.yaml
  - ./dispatcharr/ks.yaml
  - ./enhancedchannelmanager/ks.yaml
  - ./watchstate/ks.yaml
  # - ./streammaster/ks.yaml
  - ./tdarr/ks.yaml
  - ./kometa/ks.yaml
  - ./kapowarr/ks.yaml
  - ./pulsarr/ks.yaml
  # - ./stremio/ks.yaml
