---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: qBittorrent
  category: Applications
  description: qBittorrent is a free and open-source torrent client
  url: &url https://${APP}.${ROOT_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/qbittorrent.svg
  access_policy:
    groups:
      - media-managers
  authentik:
    proxy:
      mode: "forward_single"
      externalHost: *url
  gatus:
    - group: "Applications"
      url: https://${APP}.${ROOT_DOMAIN}/
      method: GET
      conditions:
        - "[STATUS] == 200"
