# This is a generic example of a configuration file
# Rename this file to `config.yml`, copy it to a `config` folder, and mount that folder as per the docker-compose.example.yml
# Only uncomment the lines you want to use/modify, or add new ones where needed

exclude:
  # Exclude platforms to be scanned
  platforms:
  - _info.txt
  - '@eaDir'
  - video
  - .Stfolder
  - images
  - videos
  - '*.Stfolder'
  - '*.txt'
  - '*syncthing*'

  # Exclude roms or parts of roms to be scanned
  roms:
    multi_file:
      names:
      - _hidden
      - images
      - '@eaDir'
      - '!images'
      - '!orphaned'
      - '!downloading'
      - txt
      - manuals
      - cfg
      - stignore
      - '*videos'
      - '*manuals'
      - .Stfolder
      - '*syncthing*'
      parts:
        extensions:
        - txt
        - xml
        - jpg
        - jpeg
        - images
        - cfg
        - stignore
        - '*videos'
        - .Stfolder
        - '*syncthing*'
        - syncthing
        names:
        - data.xml
        - ._*
        - multidisc
        - manuals
        - cfg
        - '*manuals'
        - syncthing
        - '*syncthing*'
    single_file:
      extensions:
      - xml
      - txt
      - jpg
      - jpeg
      - pdf
      - images
      - manuals
      - '*.cfg'
      - stignore
      - '*.Stfolder'
      - '*syncthing*'
      - syncthing
      names:
      - info.txt
      - ._*
      - '*.nfo'
      - '@eaDir'
      - '*.xml'
      - '!info.txt'
      - mp4
      - '*.mp4'
      - '*.cfg'
      - cfg
      - stignore
      - '*manuals'
      - '*.Stfolder'
      - syncthing

#       # Exclude files within sub-folders.
#       parts:
#         # Exclude matched file names to be scanned from multi file roms
#         # Keep in mind that RomM doesn't scan folders inside multi files games,
#         # so there is no need to exclude folders from inside of multi files games.
#         names:
#           - 'data.xml'
#           - '._*' # Supports unix filename pattern matching

#         # Exclude all files with certain extensions to be scanned from multi file roms
#         extensions:
#           - xml
#           - txt

system:
  platforms:
    # bbc: bbcmicro
    dreamcast: dc
    gamecube: ngc
    gamegear: gamegear
    gb: gb
    gba: gba
    gbc: gbc
    # lynx: lynx
    # mame: arcade
    megadrive: megadrive
    n64: n64
    # neogeo: neogeoaes
    nes: nes
    # pcengine: turbografx16--1
    ps2: ps2
    ps3: ps3
    psp: psp
    psx: ps
    saturn: saturn
    sega32x: sega-32x
    segacd: segacd
    snes: snes
    wii: wii
    wiiu: wiiu
    switch: switch
    switch-2: switch-2
    # wswan: wonderswan
    # wswanc: wonderswan-color
    # xbox: xbox
    # zxspectrum: zxs

#   # Asociate one platform to it's main version (IGDB only)
#   versions:
#     naomi: arcade

# The folder name where your roms are located
# filesystemz:
#   roms_folder: 'roms' # For example if your folder structure is /home/user/library/roms_folder
#   skip_hash_calculation: false # Skip file hash calculations on low power devices (eg. Raspberry PI)

# scan:
#   # Metadata priority during scans
#   priority:
#     # Below are the default priority values used
#     metadata: # Top-level metadata source priority
#       - "igdb" # IGDB (highest priority)
#       - "moby" # MobyGames
#       - "ss" # Screenscraper
#       - "ra" # RetroAchievements
#       - "launchbox" # Launchbox
#       - "gamelist" # ES-DE gamelist.xml
#       - "hasheous" # Hasheous
#       - "flashpoint" # Flashpoint Project
#       - "hltb" # HowLongToBeat (lowest priority)
#     artwork: # Cover art and screenshots
#       - "igdb" # IGDB
#       - "moby" # MobyGames
#       - "ss" # Screenscraper
#       - "ra" # RetroAchievements
#       - "launchbox" # Launchbox
#       - "gamelist" # ES-DE gamelist.xml
#       - "hasheous" # Hasheous
#       - "flashpoint" # Flashpoint Project
#       - "hltb" # HowLongToBeat
#     region: # Used by IGDB and ScreenScraper for regional variants
#       - "us"
#       - "wor"
#       - "ss"
#       - "eu"
#       - "jp"
#     language: # Used by ScreenScraper for descriptions
#       - "en"
#       - "fr"
#     # Media assets to download
#     # Only used by Screenscraper and ES-DE gamelist.xml
#   media:
#     # Used as alternative cover art
#     - box2d  # Normal cover art (always enabled)
#     - box3d  # 3D box art
#     - miximage  # Mixed image of multiple media
#     - physical  # Disc, cartridge, etc.
#     # Added to the screenshots carousel
#     - screenshot  # Screenshot (enabled by default)
#     - title_screen  # Title screen
#     - fanart  # User uploaded artwork
#     # Bezel displayed around the emulatorjs window
#     - bezel
#     # Manual in PDF format
#     - manual # Manual (enabled by default)
#     # Gameplay video
#     - video  # Video (warning: large file size)
#     # Media used for batocera gamelist.xml export
#     - box2d_back  # Back cover art
#     - logo  # Transparent logo
#     # Other media assets (might be used in the future)
#     - marquee  # Custom marquee

# EmulatorJS per-core options
# emulatorjs:
#   debug: true # Available options will be logged to the browser console
#   cache_limit: null # Cache limit per ROM (in bytes)
#   disable_batch_bootup: false
#   disable_auto_unload: false
#   settings:
#     parallel_n64: # Use the exact core name
#       vsync: disabled
#     snes9x:
#       snes9x_region: ntsc
#     default: # These settings apply to all cores
#       fps: show
# netplay:
#   enabled: true
#   ice_servers:
#     - urls: "stun:stun.relay.metered.ca:80"
#     - urls: "turn:global.relay.metered.ca:80"
#       username: "<username>"
#       credential: "<password>"
#   controls: # https://emulatorjs.org/docs4devs/control-mapping/
#     snes9x:
#       0: # Player 1
#         0: # A MAPPING FOR EACH BUTTON MUST BE SET!
#           value: x # Mapping for keyboard
#           value2: BUTTON_2 # Mapping for connected controller
#       1: # Player 2
#       2: # Player 3
#       3: # Player 4
