[env]
ROOT_DOMAIN = "driscoll.tech"
AUTHENTIK_API_TOKEN = "op://Eris/Authentik Token/credential"
# PROXMOX_ENDPOINT = "{{ .proxmox_endpoint }}"
# PROXMOX_CREDENTIAL = "{{ .proxmox_credential }}"
# PBS_HOST = "{{ .pbs_host }}"
# PBS_TOKEN = "{{ .pbs_token }}"
CF_ACCOUNTID = "op://Eris/7ntcze3fqqzun7huc7vyoirco4/accountId"
CF_USERNAME = "op://Eris/7ntcze3fqqzun7huc7vyoirco4/username"
CF_CREDENTIAL = "op://Eris/7ntcze3fqqzun7huc7vyoirco4/credential"
EQUESTRIA_TUNNEL_USERNAME = "op://Eris/Equestria Cloudflare Tunnel/username"
EQUESTRIA_TUNNEL_CREDENTIAL = "op://Eris/Equestria Cloudflare Tunnel/credential"
SGC_TUNNEL_USERNAME = "op://Eris/Stargate Command Cloudflare Tunnel/username"
SGC_TUNNEL_CREDENTIAL = "op://Eris/Stargate Command Cloudflare Tunnel/credential"
# CFTUNNEL_USERNAME: "{{ .cftunnel_username }}"
PROWLARR_APIKEY = "op://Eris/Media Management Secrets/prowlarr_apikey"
UNIFI_API_KEY = "op://Eris/Unifi Api Key Eris Cluster/credential"
GITHUB_TOKEN = "op://Development/GitHub Personal Access Token/token"
GRAFANA_TOKEN = "op://Eris/Grafana ApiKey/credential"
SONARR_API_KEY = "op://Eris/Media Management Secrets/sonarr_apikey"
TAUTULLI_API_KEY = "op://Eris/Media Management Secrets/tautulli_token"
SABNZBD_API_KEY = "op://Eris/Media Management Secrets/sabnzbd_apikey"
JELLYFIN_API_KEY = "op://Eris/Media Management Secrets/jellyfin_token"
PLEX_API_KEY = "op://Eris/Media Management Secrets/plex_token"
JELLYFIN_USER_ID = ""                                                           # "{{ .jellyfin_user_id }}"
IMMICH_API_KEY = "op://Eris/Immich ApiKey/password"
IMMICH_URL = "https://immich.driscoll.tech"
PROWLARR_URL = "https://prowlarr.driscoll.tech"
SABNZBD_URL = "https://sabnzbd.driscoll.tech"
QBITTORRENT_URL = "https://qbittorrent.driscoll.tech"
SONARR_URL = "https://sonarr.driscoll.tech"
TAUTULLI_URL = "https://tautulli.driscoll.tech"
JELLYFIN_URL = "https://jellyfin.driscoll.tech"
ROMM_URL = "https://romm.driscoll.tech"
DISCORD_URL = "https://discord.driscoll.tech"
GRAFANA_URL = "https://grafana.driscoll.tech"
AUTHENTIK_URL = "https://authentik.driscoll.tech"
UPTIME_URL = "https://uptime.driscoll.tech"
GLANCE_K8S_SGC_URL = "https://glance-k8s.sgc.driscoll.tech"
GLANCE_K8S_EQUESTRIA_URL = "https://glance-k8s.equestria.driscoll.tech"
HEADLAMP_SGC_URL = "https://headlamp.sgc.driscoll.tech"
HEADLAMP_EQUESTRIA_URL = "https://headlamp.equestria.driscoll.tech"
BACKREST_LUNA_URL = "https://backrest.luna.driscoll.tech"
BACKREST_CELESTIA_URL = "https://backrest.celestia.driscoll.tech"
