---
# kustomization.yaml
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./definition.yaml
configMapGenerator:
- name: glance-config
  files:
  - ./resources/glance.yml
  - ./resources/home.yaml
  - ./resources/homelab.yaml
  - ./resources/staging.yaml
  options:
    disableNameSuffixHash: true
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled

- name: glance-widgets
  files:
    - ./resources/widgets/nhl-today.yaml
    - ./resources/widgets/nodes.yaml
    - ./resources/widgets/service-status.yaml
  options:
    disableNameSuffixHash: true
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled
