---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app david-driscoll
  namespace: &namespace github-actions
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: gha-arc-controller
      namespace: *namespace
    - name: gha-repositories
      namespace: *namespace
  path: ./kubernetes/apps/github-actions/runners/david-driscoll
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  force: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
