apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-user.yaml
  - postgres-user.sops.yaml
  - postgres-superuser.yaml
  - postgres-superuser.sops.yaml
  - donetick.yaml
  - donetick.sops.yaml
  - gatus.yaml
  - gatus.sops.yaml
  - homechart.yaml
  - homechart.sops.yaml
  - immich.yaml
  - immich.sops.yaml
  - n8n.yaml
  - n8n.sops.yaml
  - pulumi-operator.yaml
  - pulumi-operator.sops.yaml
  - romm.yaml
  - romm.sops.yaml