# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: questarr-postgres-password
stringData:
  username: ENC[AES256_GCM,data:PySxwSFzumg=,iv:sh3d612ePp3hlXKapOfQ657Mogkku4eBpUd24eJzBwc=,tag:121UB7x4pZ356dIeuI5HPg==,type:str]
  database: ENC[AES256_GCM,data:meFDXxeKEMw=,iv:rfakShK+T+RAUxRdBqGUN7jKuy3OefJS8WvYarV9u2o=,tag:f28yyrhnEJE5ypUmId2rIg==,type:str]
  port: ENC[AES256_GCM,data:iPKVIw==,iv:kcwpimvJkyHQiHSgvWWxExq2nnCl2K0Qk7BAh0x0h84=,tag:6vXjZ8O/QZnZitx9EhknNQ==,type:str]
  hostname: ENC[AES256_GCM,data:96nGI1jzhoLbUOn4xhCbUgAJrGcsPxiGj8auak5ZeV3+XtEYXfE=,iv:WOEO+ZmQ6h8ieUXejCwyNHqSQuJsxYe9TPSgwwLa4/I=,tag:RB5b75H5gStA/OG76rC6tA==,type:str]
  password: ENC[AES256_GCM,data:/H2wR3zFQXlcQTvmYYna6okjTJdAKr9JWcK3z62NEBA=,iv:n90VbwQ8r3YTs6eVrBJPUaFmkOwtPWzN5t0OK9y9p7o=,tag:R3Z5E98e6EOrNOxfFaQ5cw==,type:str]
sops:
  age:
    - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcG9kMXVvMFZvUlZQQjZU
        aDR2MXlwMm1FOXhqWjBQWVBwcVMzL1p2ZFJRCm5oTHJzbjRsN1oveThHNTdVaS8x
        aHlkblRGMEJ6WmcxOHlrV2thRFRDY3MKLS0tIGtabTl1OXUwSll5aEdFK2oyanN5
        U2s5bSsvUjFxNm52TzVwS0w5MkxWbEUKP5vzRAFXcJq3Ren9x97aRAxJhziAGiaR
        fLKf9wVAAzFkIW/+wOCmsxS5K2S+dgGuv0+ul3Z1jz7fim5BsG3lNw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL1FjT2pQMThZK3FFVWNT
        NU9JdFBOYjRWdWxNWmhkVjFoZmcxZGExa1hrClJvei8xNEJNUGwwSXNKUWpVSnJq
        YXVFUXFieUR1WHB0dm9BNWt2c2FzYlUKLS0tIGNvbHNhSzFNSSsrVENyTEdJbWVX
        TXRTQ21menFvb2VMM1Q0d1ovaGVrajAKWRFGEfWKUItmoyVAUTw1ykwoQEz4Z+aa
        gQRgQlJ8m+ScX5aMaCLqa8Dd7cHjjt30B3ib4NLMNxeLfoDOVe2POw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTU5qNGlqWHIxWTYxbnk3
        VHU2ZjlvbEZOWVdBWjRTeDdaSWVCL3FVclVvCjdmUGF4N09iRkpScDVaa1JnUkpD
        clhZSlROOXBKb1pHR2UwYml6aVhPeWsKLS0tIHFteGZFRGo4Q3dCZlhuQlBVdyt0
        ekV0UFFia2NDN3NPeW1lOGF4WDVLa2cKvXDk4QM2aiTR9NeqwPq/Mo6E+0O9mN60
        v6TKqr/IK8Doh4srC5/+V1AnzlYqVZUg/rseT6KgqiWwSSc2wQSCjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T01:52:54Z"
  mac: ENC[AES256_GCM,data:fl52ZBFwty2KJwXIv+8GHmMmr5GAcJ77128hSWByLqdYEYkM1UrK7DwHCMmm89pLOstmFWutHJfw9/QT/RgDZVAh2YXDcbxmf10hJvloh8pWz+OEZmq4kNXsOD9zgtJVtA23P4629fQ0ORt/pGIzTx/il41KBRbyQpbmWNleNYE=,iv:jv7HgvW+7eo/j+F2d3+UxcMg1rqI8PhEGpSL3Aqhlx0=,tag:5plAgkMH8wjy/+Cts9zHjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
