---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Pulsarr
  category: Media Management
  description: Real-time Plex watchlist monitoring and content acquisition tool
  url: &url https://${APP}.${ROOT_DOMAIN}
  icon: https://raw.githubusercontent.com/jamcalli/pulsarr/master/assets/icons/pulsarr.svg
  access_policy:
    groups:
      - media-managers
  authentik:
    proxy:
      mode: "forward_single"
      externalHost: *url
  gatus:
    - group: "Applications"
      url: https://${APP}.${ROOT_DOMAIN}/login
      method: GET
      conditions:
        - "[STATUS] == 200"
