---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Dispatcharr
  category: Media Management
  description: Dispatcharr is an open-source powerhouse for managing IPTV streams and EPG data with elegance and control.
  url: &url https://${APP}.${ROOT_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/dispatcharr.svg
  access_policy:
    groups:
      - media-managers
  gatus:
    - group: "Applications"
      url: https://${APP}.${ROOT_DOMAIN}/
      method: GET
      conditions:
        - "[STATUS] == 200"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}-ecm
spec:
  name: Dispatcharr Channel Manager
  category: Media Management
  description: Enhanced channel manager for dispatcharr
  url: &url https://ecm.${APP}.${ROOT_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/dispatcharr.svg
  access_policy:
    groups:
      - media-managers
  gatus:
    - group: "Applications"
      url: https://ecm.${APP}.${ROOT_DOMAIN}/
      method: GET
      conditions:
        - "[STATUS] == 200"
