apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    annotations:
        reloader.stakater.com/auto: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    CLUSTER_CNAME: ENC[AES256_GCM,data:j3wBvWc3ZHJJ,iv:Go9cpI1QDPb23sUOSzZGzjmhYb9oPAQgvlanT4Sr3ck=,tag:4EOTBrVtQRbEikjwBx+/Ww==,type:str]
    CLUSTER_KEY: ENC[AES256_GCM,data:ojwPib3MGMGc,iv:IeAfFLWw8f40S1gZhI1Fq9IbROvzqfGeuMyO8sPrtm0=,tag:jiQJUaE2+zW9S9VjgB0zyA==,type:str]
    CLUSTER_TITLE: ENC[AES256_GCM,data:Dxog2AwRAVtD,iv:JVIDil7IePQk/UleW8S01dOpGaMBUcQ5NiT8cwM4jpw=,tag:A00Eq5dV0CCxbRKa3BO/qg==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:MQYySwerqMGm/RIU9hH8drCqRlqz8SQ=,iv:k6zuyUoleqghPqIsLz5k5kG3NNBBbEMTJ0yWNMKwBf8=,tag:kAKZM+M5icP09l6Id60J6A==,type:str]
    CLUSTER_IP: ENC[AES256_GCM,data:/Oy0ThGDgxaxaQc=,iv:5Dsji1/JrhoxwAnRWN9LOSzQIm+lYhT6F41Mi/znzho=,tag:ESiPRQQTMKCs0hQNld1uiA==,type:str]
    CLUSTER_API_IP: ENC[AES256_GCM,data:g1zSgHp7Y5OyJ7jcKQ==,iv:9dv2ghGZLhaEb59lFISmHNBxg0bLroM9AAvybO6tcAw=,tag:JDp2jVurKmf/cLFUnaaihg==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:AOoiTpBnySMBLJOveFFN1s9LdNax5ASpMPh8mS9MLMA5HCEHrQgTQEQ6,iv:y3rVPuGbkqteokjw6jbJFWZn4V+UMbNvynUFV+VYU7E=,tag:7weXYIMPPYrjXoPmtSoALA==,type:str]
    CLUSTER_TAILSCALE_DOMAIN: ENC[AES256_GCM,data:uGqHso4627/mmo3iLG2hc5ioRLSuJ6TsC+DZ,iv:XXrwRycwDKM60MTobRwnZPx47Yzaii6XmDpgJIrypOs=,tag:I0jIoLFKmO+OIrbrZZJcDA==,type:str]
    INTERNAL_CLUSTER_DOMAIN: ENC[AES256_GCM,data:LqXrdBY4JqOr6D//sg==,iv:Q82eqTW0ZQmsTH0u7NvjwCWJ6I49d0ZW1F+8rxYNAjE=,tag:6eeMKaaCQX4DXzesHd0A1w==,type:str]
    INTERNAL_CLUSTER_SERVICE: ENC[AES256_GCM,data:knEFwUPjpAdM1JX610Pkyl8gUH6VSXAmEQLr,iv:S5mK0xmtOujRnkbCGRfSMg7yQ3618DrdtKRY7hMMflQ=,tag:dvFSIZFgn8ezR1fgm09TJA==,type:str]
    INTERNAL_CNAME: ENC[AES256_GCM,data:AGK4vMIqU/kZ,iv:uzZCvEBnJUqj2WsLITnD28+mozwhCTEbe4dbVYIVhWA=,tag:BLu8QsDQSDkcg3RxEj0vcA==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:9sci9OEdyF2y+SyXAOsY+sz6CNHUMz0=,iv:5ICjyPxVKcwPUhV18Lfbn21c29Wzd0CE/iDtZrij0UM=,tag:ArQfNWb9fKBNcdz+AXJWwQ==,type:str]
    INTERNAL_IP: ENC[AES256_GCM,data:IAdgr/DzuQWOHyDFBg==,iv:UPUgbDkLl3P+K4K3ze2rLQAjHSpf5+q5k9NzVZWcCS0=,tag:n4PN+3vE9ymVDxjNUKQBaA==,type:str]
    INTERNAL_TAILSCALE_VIP: ENC[AES256_GCM,data:DSWdP7VqzPqHvsjRcp7m,iv:DnrmzUwR0iiNpQGJljC9Tr/FdJ/ZQuLnqNWB7usqhyI=,tag:8GW4XPxZtlVMI/TC141R8w==,type:str]
    EXTERNAL_CNAME: ENC[AES256_GCM,data:KmFvhA9b5Bui3YOU8rrxsYeb6C8=,iv:E3xSC820cHIy5+/4Uj1qoFNwHgj1JX0301SO0uZ4sII=,tag:arIOutQrSBALhVskdOcvvQ==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:wJcaSyi+076BVaazvHXX5avXSbz8LS/okhxJvlYhhLO9hA==,iv:V+uXP3la2fGXTX+Su+0CNEaChK7BcHMSqC/rcSZk+Js=,tag:KC8VJm17wKGXotxafTppWQ==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:YwVwU0XuoMDdaKMQRw==,iv:c2/xJBPtKxYVEkFSrDr5D5gvEATX0KDuuWanPLANDyM=,tag:atKZXg2uqkRYg37iOYLkwQ==,type:str]
    EXTERNAL_TAILSCALE_VIP: ENC[AES256_GCM,data:OLvkRHQNaL7oIfbXUXlX,iv:PhmUR8EDiDX8Aj3GkoSWy8DbLrK966Wn1lP2S5tKCWw=,tag:wQuuSR244NnlY9Ec2YmDyA==,type:str]
    RUSTDESK_IP: ENC[AES256_GCM,data:CLohZMWGfjkfIJCbdw==,iv:nrPmoL3VozYJLdE8BVCSALY86jFbqZzGvSxbFL/gf1Q=,tag:KdmFPB9UUq4R4uh7/PXg4w==,type:str]
    K8S_GATEWAY_IP: ENC[AES256_GCM,data:DW+KD9hu3qNqoZgJsQ==,iv:FLTUr/NMxVwxzyyEVH5PyksV8P/Q33ks9pCS6LuUYR0=,tag:FuYW+huM+IthlFfuWr/j/Q==,type:str]
    TUNNEL_DOMAIN: ENC[AES256_GCM,data:v4lBhYmUVbXY9y6mUlfmU0HKXQE98bC6K3V385Utuq/LTRAo31nNX8osktbpd9WZwUSfFuU=,iv:ba9clWkBNOGCR0BnnzUe2gUTBPBkWGz52BT71SqPEGU=,tag:C9fDWacT1UbtrsTko2CnxQ==,type:str]
    CLOUDFLARE_TUNNEL_SECRET: ENC[AES256_GCM,data:xzJEMBRQP/UkbTSXs5W8SSNTTPIcba2IgmNqX2tL7ikMR7kD/if95aXyUso=,iv:HokNTPHL5b620uwvTKwiKnPWR4qJ1FX9wK1ylnyQPEs=,tag:CwWUiM1CsLM2maYJlY3oaw==,type:str]
    CLUSTER_NETWORK: ENC[AES256_GCM,data:cCgUk5fe+DW+mBTM/g==,iv:sz3bt7pXScBv7qS+VZpzrBqgsYPRqcCsOGLOdHHXSfg=,tag:YpZxpskvzCuNs/dtUKT9ww==,type:str]
    SERVICE_NETWORK: ENC[AES256_GCM,data:kvCpYuXnfDggiFPNuQ==,iv:tEsA05c8a7VUZLXXINOeATfM+PlgR2mcR31tUpRcJUY=,tag:edOcif3lhXgnXft/sXaVwA==,type:str]
    TAILSCALE_NAMESERVER_IP: ENC[AES256_GCM,data:7iVUDZZNVlbYhfa3DQ==,iv:XmkWdQ80EQcjM6tgtlydHSTm/mjX0bSuavBirjkkO/I=,tag:mHbarETo7ZcFh769aPj7qw==,type:str]
    OIDC_ISSUER: ENC[AES256_GCM,data:uRsBNf/za5V53U3AwYAhPN3wKBwrHXQ=,iv:AYL3qOsTv1NC068m3xcVLmqAl43wBJ8EvCtF29YeHWk=,tag:EwSPyhpj8vCu5ZFb6JQ72w==,type:str]
    S3_VOLUME_CAPACITY: ENC[AES256_GCM,data:fyg=,iv:RdwBisKkBEx9ssjj+ZerVcTuC6HDzd4Joea0Z5mZSHE=,tag:rZgaekpwLlp8TVE3l5ryHA==,type:str]
    BACKBLAZE_S3: ENC[AES256_GCM,data:L4C26xuqMi/u+wxQalNPZxV2ha2XnQ==,iv:MnU574wuHuC6qvrsr5baO/EOAvVNj80uOUKbxJOsbwg=,tag:PFzQJrglBu0uUWU32TYJFg==,type:str]
    BACKBLAZE_DATABASE: ENC[AES256_GCM,data:5GL/0JdDiwSagGH0/Y5FtkJqNdAcr+vO7cmQY+NICA==,iv:mnafR6QUV2fi4o+FgcOCi7ITkyt+w9kVxyRXW645nq8=,tag:UsAUWJ4K8sDTEPm5UNSoHw==,type:str]
    BACKBLAZE_BUCKET: ENC[AES256_GCM,data:iK2pK991WpEd,iv:Wma+XiaCL8QNihfD/eNU2ESGEP2bXo7WoGxOCAIvFaY=,tag:PZAnYlm7YzK727SmdM8s0Q==,type:str]
    BACKBLAZE_DB_BUCKET: ENC[AES256_GCM,data:zD72iFm5/P0PR5FX,iv:gEsDka7tlqgSVcoRb4hDC4Jul5epzXM7BheCExkkELU=,tag:2aSokn7iC4MK90ybqCUMSA==,type:str]
    POSTGRES_REQUESTS_CPU: ENC[AES256_GCM,data:AHWh68E=,iv:cJmMSfpPKJtiC7wBqy/1GAO6z2YnDwPI2HXOhlAeHPI=,tag:KkJAb3kObQkeDoLLZYQPHQ==,type:str]
    POSTGRES_REQUESTS_MEMORY: ENC[AES256_GCM,data:ViYM,iv:14acg37KTrCoB95WP2TJm8Ea95p0JVjIyhrFhzMNxRQ=,tag:E8NME5rcIbrZBYgrDrmYBA==,type:str]
    POSTGRES_LIMITS_CPU: ENC[AES256_GCM,data:b2K60fM=,iv:JMbO4prTsU5F3U5PsquyPkow1RyU735QAbY/wRiCY1Y=,tag:YBadWpQiABNkfnHI9zn9WQ==,type:str]
    POSTGRES_LIMITS_MEMORY: ENC[AES256_GCM,data:Y/Zl,iv:t2VuUIJDCsGmxzxtV0A1tiyDr/NOjkqgZhE/glkvGCI=,tag:T+ksJ9p42JkSRYeyX6KrOw==,type:str]
    POSTGRES_SHARED_BUFFERS: ENC[AES256_GCM,data:ZIG1l4UK,iv:oYABxq+p/cl6Ac3rvfQC74EySdMj6ndi+kYjQkz2A/I=,tag:dmLQ/CVkfvhOKTQapBhpjg==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:g+qcZhvQDPkiLVA2pEXcwt+pHK4qg3kAfVef9yHyswmo+aX/m/itiIYattiSgQbz6q9z,iv:N5ZaxC9q4QiMfeehtm0INhwlzAlXTBoMaai51ug6Yps=,tag:0lB5ELfoXr5c7/+X1gOfwA==,type:str]
    GITHUB_REPOSITORY_OWNER: ENC[AES256_GCM,data:taIS4Lwqqi0+Qt2pC6t2PZjOr6wnCeDhZYcD6xjmFCI=,iv:6lKKS4Hq3AF5dB8vXt+XZJpLu/bpk8KgaClr0IK0ft4=,tag:aoEAxN8kXdzRfnqImpM4YQ==,type:str]
sops:
    age:
        - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eWZjZnpsUS9FSmxvUkhK
            bFNqT2NiUmFpSkJybWJtd01PVGJ6Q3YvUTBZCnBOREpQdGN1ak00TnlLaHVLRWZ4
            Yy92V2o2S2xTdXhWbjBYTmlnK2FnT00KLS0tIGc0TVlxWWxFVmR5OEtFcDlrSDkv
            bUpTeGxyeG9ZdEFibGJmYm1IOEJsSWMKeVhr8T4/GI9OSKXfdsARHLwzgMHA1tY7
            Knzx1BDwHzMQ2E/iaEw36BWxL3RgOkOaozJyquPOZUeqaGTIKtDSSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdUMrcjRwWmdFRk94eEFJ
            MVREL24rSGdFSElhYmhyclpyR1NTQVhrYXpRCld1aS9weUYydnZZU3NzOHNxSDlo
            MzRUVFZDelI2UGFuZW1adE5xb2NkQ0EKLS0tIC9WSG9OdEdsVUNodjVqNkZ5RVBy
            c1JvSjZnY2VPeW94YVVjVmlqaW01ejQKH/QNrCTDvrkWaLjzg2vKDzGC9kzzEscH
            8MwLdYtlSRfm6CzpC5f/hNbz94O9yDNWyEXv1t/PetpvHKZdiGSOvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZXg4U2hyZFpVdHdxWi9u
            TVArb3c3aUpGMFE1MVVZaDN6dlB6UTZmTmhRCm9KaHZFa2E2UTVFaHY2dW4rcnBR
            eHpCNjBLR1pQRHczU0pLQm8rMThBdDAKLS0tIHBSS05IUGpHVXZHQ2N2WWlDTFM0
            RjBsaGlYWG9IWTVmL0JUT1NrdHJhYXMK3Ao8vdR3ZhR1RB+aC459zFtsBA3z+a16
            89cYeXXJyTTm8FACRPWLINWGE22NvZGCmKPfqx5eBw6T/nIToDLqRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T04:29:58Z"
    mac: ENC[AES256_GCM,data:R8dzZ0hQgAAvraN4zq3WoAls4f9XFpgFm0Rfg4LNyprP3dBgo1Cqt3dxY8xq9KfEBBLH4JcA6DNkQgu3mKzpx54NZsBwjUWB5Sjs1yrsotVwSgvn7ecNwvGoSQU2ZeNrqA67f2RIFfMjDpcltGyGY8euZk5ugz9HaBd3vX7oeYY=,iv:nPYY/RPoPGWW+1q5Se0QQrRaSjKGTGElOsPWU51ZrNY=,tag:lyFb0k7D7y8TMxQXrDkmfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
