apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  annotations:
    reloader.stakater.com/auto: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
  CLUSTER_CNAME: ENC[AES256_GCM,data:iTWIXLYcIkvm,iv:GsmJ9PrjOUVyhi56NTniArRiXwEb7/iUF8rS5OVVubo=,tag:BEe3mA/fRXKPB5YCLcwqdA==,type:str]
  CLUSTER_KEY: ENC[AES256_GCM,data:IW4XYVAcVSrR,iv:5mM5PY3yp5Gqd72ffTc5Ag2tixsPQiQWsXa4+vRo1VI=,tag:KxXiiAa6N2zl/2Uruj2BGw==,type:str]
  CLUSTER_TITLE: ENC[AES256_GCM,data:mmiKPhyDCloy,iv:5nUpt3kCiz0x5a7jpmijGiGuGJBjXk7tQyGK5bkR1Ww=,tag:MX+J16GD9MpJxq5BDLYZ1Q==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:8Wh2NCoRQml2aBEAtbhhLPWxPAjNXZQ=,iv:KBW1Pr12I/6AiZGhtFa3BfdxlPhHVyVHqBWDMYQhByg=,tag:NC0krZDvk8W4ByJ3N0117Q==,type:str]
  CLUSTER_IP: ENC[AES256_GCM,data:SrQ/3EZkUXrlAcM=,iv:qRxAVeuBGnC8qjTzPJ86y78rqjtZ5KgQjpNWvJyR1xg=,tag:9D54eVyHh6i3lUjb1xsRqg==,type:str]
  CLUSTER_API_IP: ENC[AES256_GCM,data:NdYN7v9r9MzcVPT4Hg==,iv:Rg2LOr50ioyCY6pXuRlnMnjRbNP7ytLlxaBTQyIKwDk=,tag:dh+HbSxjlbj0SIi4ZrHdmw==,type:str]
  ACME_EMAIL: ENC[AES256_GCM,data:+lUQv0E0rmzOOAi1cogD3psC/7VyjMRF1uxNCLuRQWjItlXzdJrIJUAY,iv:i+sW0ZwC/3FDVWb329mrOv6tQxsBCCiqtX4fm5zdhlc=,tag:Wsa7JHQErVcwpja/FYJYew==,type:str]
  CLUSTER_TAILSCALE_DOMAIN: ENC[AES256_GCM,data:RXNT/Uph+AxrgE4gmshIUd9GU9PlRdiVTJLL,iv:LgspLTIAOsVZPOB5GkhFjV2mo7/L7PpiiMke4kL7aDs=,tag:ltQNaAfgUTFXJBKwUflKzA==,type:str]
  INTERNAL_CLUSTER_DOMAIN: ENC[AES256_GCM,data:a3X7V4FN3h1dUVo97Q==,iv:cqPfpcRxX6YvZ0wX84GpRLslbnenlJE71ICv3cQV0tM=,tag:JNVQTbOjk+Pp1NVzXBDDfw==,type:str]
  INTERNAL_CLUSTER_SERVICE: ENC[AES256_GCM,data:p3McXCTOt9iJv/Nqrvf49qt2fu80n8IhwYnT,iv:5POPmhE89cn4vTTRM1rlrJdv/TyKXt39BgZy0HmFgTc=,tag:rEJiMmB5eNtwNPsTNsS8mg==,type:str]
  INTERNAL_CNAME: ENC[AES256_GCM,data:xHS6Di2FYjMy,iv:TgViXL8pqmqrAi8Qg4qE+saqWGTJEUQD8641K6ys3cY=,tag:FyFQlVLFotIoBsLRFHYHNQ==,type:str]
  INTERNAL_DOMAIN: ENC[AES256_GCM,data:0sqwmyzuYKiTcnwupqjgqNp/2C4LC40=,iv:+LdvcyLJS2vEfoUPUT+1N4F1bqxvQtnCJxIupvXhA3s=,tag:DOa5AoaRsSyKdoJV9/8rFA==,type:str]
  INTERNAL_IP: ENC[AES256_GCM,data:3qWy6Q6HlsnnITqsnQ==,iv:BcE7gIwJI64LgtDLCcbXL+B3WgADaRzLGdZCQHBbM3o=,tag:zQeImnAZQe9YOCngPOvL/A==,type:str]
  INTERNAL_TAILSCALE_VIP: ENC[AES256_GCM,data:HsgLiwVUAIvGRKoEgLj0,iv:Q0VrbDH22d1z7WlL23Lcl2g9hnfkFafSbiz+K7/TPiQ=,tag:hY464Zn4HRFp+bpvckR+Ew==,type:str]
  EXTERNAL_CNAME: ENC[AES256_GCM,data:pbqZdxnjYXt6t3/Z4bEDr+iJf14=,iv:r6rdZhBx9fHG4YENy8M9Kd+yIaMnUHfWIVTXQkE2nRo=,tag:sU4yjJOoRsSw1HDptRpm8g==,type:str]
  EXTERNAL_DOMAIN: ENC[AES256_GCM,data:qyAx2N2iCj+XJj3nJtstUadPh3idE23iTI4t25Hw2sTZ1A==,iv:17DStSW9mredsg6uqfZnDjECrf5eVqYRseyumiega+8=,tag:ko0K+jNLlnIg/qWIcbDRKQ==,type:str]
  EXTERNAL_IP: ENC[AES256_GCM,data:HAr2G1+jTikjYkfN6A==,iv:IeVawRPfOxEWcdIeAUby9mPGJP3xFVN/nwoje3FA/CY=,tag:QklES2FDQrD+xwP7MCMbgw==,type:str]
  EXTERNAL_TAILSCALE_VIP: ENC[AES256_GCM,data:HIgsdANALrW0aG4Rjtw3,iv:hjgagqOmDhYv7tTjp0dI5ua2Fo+YKbFRQQma4kkY0+M=,tag:DUYdSIFh8BxLNj9DE+jBUw==,type:str]
  RUSTDESK_IP: ENC[AES256_GCM,data:cToGQfWmjrAjqU+PGQ==,iv:DB4eTdS4rxNOetq09AfvD+QJha7s/NcWWyS51TIPEUo=,tag:V0/+FYBDr15OeIJpSLJlUg==,type:str]
  K8S_GATEWAY_IP: ENC[AES256_GCM,data:7bMFpUeJymVoPPGDXg==,iv:UI08WFCo4OI7G6FdapRU4QgaoG16Zc7HEgIkeNCuTE4=,tag:DBM9kHhPrbGNwHJolDjELQ==,type:str]
  TECHNITIUM_VIP: ENC[AES256_GCM,data:NOEinr0O3cP1WN6vHw==,iv:029UqYoXc/FhF3WJYBVvMSjq1JSDyjs5Akjqzfm91vE=,tag:M5k1QFTomXorsJI3tUVl2A==,type:str]
  TECHNITIUM_TAILSCALE_VIP: ENC[AES256_GCM,data:aCAR2Bb6hl4Mhqa8ji0S,iv:NAvwwUradRQ0zv/nM9pm/rtuA77sxgX8VRs2OTgfnuM=,tag:GQQ1OqMj6ejLn/oQ8+6tzQ==,type:str]
  TUNNEL_DOMAIN: ENC[AES256_GCM,data:Br5We3y2mk6zThUP/X6pZpFWcmzPAol2gf71xiHHUH2p0BZNzMRZm9wvaq0azkEacW2T2qY=,iv:Rn6c99bckCg5iBWD3ngwe+ihDoaOmvZ4SPda1XcuI5c=,tag:RWUHg4dVAi25HgjzlX9PFg==,type:str]
  CLOUDFLARE_TUNNEL_SECRET: ENC[AES256_GCM,data:dbAfKJO5sunSkOHfukgW/hZfO6Tf8icbWZO+s4kLk+R54ucIr7OpjY224ns=,iv:eR2J1XhUMVdlbeTXtOahg5Ji/NqtJ5iluauIRXXH3Ew=,tag:yFGotbtnr4EsvLIEu09h9Q==,type:str]
  CLUSTER_NETWORK: ENC[AES256_GCM,data:gc1FSRgHJj3RvNBLVw==,iv:o6lU2TBQHHCQAZ/PTF6jHbfxhfZkoCC9cZfBQXrMDmE=,tag:WmKpAXFrS4GTPE/ym974Nw==,type:str]
  SERVICE_NETWORK: ENC[AES256_GCM,data:OYYyaJQSiYhMSzp5dA==,iv:5n0EEeJZ9NWpb9JbU2LQiNmClq710KfdhHWouzdmfDI=,tag:ECme/GkPxWDo5MR4oC2zIw==,type:str]
  TAILSCALE_NAMESERVER_IP: ENC[AES256_GCM,data:N+XeWtXCRW3qrQTo8w==,iv:CmOlkUBkPFTqYaAvKBlMBIr7ZsxZaL5YLqVbCABJjfQ=,tag:wTvfivpy12Ge+/3UWdolNA==,type:str]
  OIDC_ISSUER: ENC[AES256_GCM,data:d71MoVhQmW+6RAhz43iFt0KUrexMRNc=,iv:iQTZ1+fODilvlNacqslUWPHvRt/647Yqpphv68oHvJU=,tag:D+KXDsTtQVzzxiO4ID59cg==,type:str]
  S3_VOLUME_CAPACITY: ENC[AES256_GCM,data:kpM=,iv:Js0tqJr7ytpz9WwhuluQi4PSh5qF4PM0Q8LQFoGbo5c=,tag:cvJjUkXh7n/URTWOUOe6pA==,type:str]
  BACKBLAZE_S3: ENC[AES256_GCM,data:Y2caBS4WjXRlQqtJeTD/j5nKnTMmeA==,iv:qROO7WqJojF3e802WCsPNKIfGXX/+0MYkvy/j2hhAZs=,tag:o/xfU24YTIwBShcC4Zp1tg==,type:str]
  BACKBLAZE_DATABASE: ENC[AES256_GCM,data:Q+3ycfKBH1Twq9ADWjaeDXomsbPuQ3D9LNMeKaOkEw==,iv:AaNcxvq5Saud2q1TnuLDOT8m3ZGM1t/7GivYaEB+0AU=,tag:UI+AUEBkhMDfiSSGIG6iwQ==,type:str]
  BACKBLAZE_BUCKET: ENC[AES256_GCM,data:xj2NGQgyCHhN,iv:qe1iOlbdsasSI7u71Dvds7Z0fNiDVmQAg6+8XnY6Rq4=,tag:HM9ukw/C9QOym6Po6Aa8TQ==,type:str]
  BACKBLAZE_DB_BUCKET: ENC[AES256_GCM,data:jrEXnY4ahbUHnKVu,iv:7nkKLDDYm1EJB55oMkiqwRK0IL0jYZ3EoJIAC7QKSL8=,tag:xGMcDr42Oepl667x59DODg==,type:str]
  POSTGRES_REQUESTS_CPU: ENC[AES256_GCM,data:lLXi3pM=,iv:TIMCJ9PRe8+GSEn/Ccb1I0pZxn7CQ2gNhw+RPpRmBVg=,tag:XqY4DcrLTdO+Ajrb70pWuw==,type:str]
  POSTGRES_REQUESTS_MEMORY: ENC[AES256_GCM,data:qvl6,iv:YsazdCpopiNV+AE9GSw3Xw09HeFj1BwRgI/RrqCWjfk=,tag:8ktflpplA6/anIHyo+PaUA==,type:str]
  POSTGRES_LIMITS_CPU: ENC[AES256_GCM,data:hgHY008=,iv:rdiFUAWY/6VFrB8TVZGgpTCk/wYXwMXYU8mpbJMIWTo=,tag:oVIBOgy50C4UWXxz0ppuNw==,type:str]
  POSTGRES_LIMITS_MEMORY: ENC[AES256_GCM,data:nQiU,iv:QkKwGty0j3b54HrR8TmjF9lbue5HAaEbRIbTQX9QQ/c=,tag:KVv77gcZurngTW760yMxfg==,type:str]
  POSTGRES_SHARED_BUFFERS: ENC[AES256_GCM,data:3QaaA25u,iv:FtSkfiZ276FdIQhPJDcDyWgB/OaXxe0ISQEJA3qdax4=,tag:PvPpqrznBM11eJ3iQRWdXQ==,type:str]
  GITHUB_REPOSITORY: ENC[AES256_GCM,data:7sp8QPuuBqaaQfmd+zRTXqGHn+meSbmHycGRzSNxXpsMtf2FOnajfD5FgXj42f1ItvZn,iv:P1MDbcrKicHU2XSn3uFU6x4KB2uoonsXbKYsDb9Eous=,tag:UAg3m2dgJFu0u/ZksLKKwA==,type:str]
  GITHUB_REPOSITORY_OWNER: ENC[AES256_GCM,data:2Up1wzZQPU59gSRviWoDXLaGBuo2udlvB3nRRmDjTuo=,iv:QxyvJcUCxlatbOAyPFV91238e3HNE/xF4w03C6yPlKc=,tag:5/aJb4HlYx56p6Lgr05jow==,type:str]
  QBITTORRENT_IP: ENC[AES256_GCM,data:80uKuzx65aHgSWvnCA==,iv:CFem/Cwu0aZqSylAw0a0sZB0ZOo6HzCxbEyCkvCgMWk=,tag:Vs8USb74JjAKOc7JVbIqKg==,type:str]
sops:
  age:
    - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dVpxTWxvWGd3cmlXNkM0
        RzMxTWh5eXdlSERTbklMUGVuYVF2V1hIMlhnCjMzcDRlNVZtQ2hzYndoV3ZkT1Rn
        cGlnZGhnT2NtZjY5Ty9TY0NtN2lrSWMKLS0tIEkrMzdJR0wvbXRaM1VHOTBzU29Y
        NlZuUitMSTBidUlNTlJtN3B3Qk54cW8Kgb/NKRdoI+lktDCLuGY8cR8CjW9jgKOp
        9lk1TPxVl2k64KY2XD4QcvTV8hmhavJZKJaOuSC1dwhH71q9gSV95A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK3g5djdlZmlIY3AzWnlV
        NEFYSmlZNllJSm02dTBMRHcwUTNWOVNRTkYwCjYycHlxVGQ1UC9ENWxDM3dLVDAy
        NkdIT3VTN05OUUpOckYyUkE5RFovcGMKLS0tIDBIY2h2S0FBUmVkcTBicnYycENa
        bGJtK3RYeWdiSzVQVXZ6WlBwM3Qxa2cKP2DRvOsLLNvwL4yts7E4qDldEm3xbggs
        vwlOjHZMLGpJ6its9oansHk3/VttFW+NjX3TqexaHdURBmumqByGdA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcHd1ZE4vUC95YlpVV3ZU
        aGhyWG5yTDRyU0RjT1FaMkp3Vkk4QjJTeVdZCjdjM2xIcUx5MjVSVWdPSGNrNmRO
        NUV3ZjltODJ6ZEt4bFNFKzFjcEowcE0KLS0tIFNpLzc5WjN6dko4ZHVaZnl3OGhz
        Q25mOWZKT2Q5bHM5SWRoYlBTUVNtZUUKwuHCXkdMvtjaZg8ki2H07Djb8YmFc02t
        D/V352D5bZD2GBUOMjGbcrix2uj2wt36rAUH1nuOahVSDh6SN9CZ/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-01T04:17:37Z"
  mac: ENC[AES256_GCM,data:CcUFA4XizQGoMWvGD9txJ9eUj+mXj+e8fpZ/gPW+OZM64uvtHXi+Bc55LydDg5zHtxQRaOnOT6pUdtBsfqlXFw/mCAa4k+OxGlXs0U/5Rg+gcK47ICBq577gDO4IHhmr886UE4n/RcSJsM/49tOfJdvzsooropL7kWKmaYt0Tow=,iv:BIgM62o7I53oFa3ilW59MLI+ecrY447+WX3S7aeQCq4=,tag:cVs2Lwg4/PRJTmqnBGXzUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
