---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Trilium Notes
  category: Applications
  description: A hierarchical note taking application with focus on building large personal knowledge bases.
  url: &url https://${APP}.${ROOT_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/trilium.svg
  access_policy:
    groups:
      - friends
      - family
  authentik:
    oauth2:
      clientType: confidential
      allowedRedirectUris:
        - url: "https://${APP}.${ROOT_DOMAIN}/callback"
        - url: "https://${APP}.${TAILSCALE_DOMAIN}/callback"
      propertyMappings:
        - email
        - openid
        - profile
      includeClaimsInIdToken: true
      subMode: user_email
  gatus:
    - group: "Applications"
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
