---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Lidarr
  category: Media Management
  description: Lidarr is a music collection manager and downloader
  url: &url https://${APP}.${ROOT_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/lidarr.svg
  access_policy:
    groups:
      - media-managers
  authentik:
    proxy:
      mode: "forward_single"
      externalHost: *url
      skipPathRegex: "^/api([/?].*)?$"
  gatus:
    - group: "Applications"
      url: https://${APP}.${ROOT_DOMAIN}/ping
      method: GET
      conditions:
        - "[STATUS] == 200"
