---
global:
  resolve_timeout: 10m
route:
  group_by: ["alertname", "job"]
  group_interval: 10m
  group_wait: 1m
  receiver: 'forward-to-primary-alertmanager'

  repeat_interval: 12h
  routes:
    - receiver: heartbeat
      group_interval: 5m
      group_wait: 0s
      matchers:
        - alertname =~ "Watchdog"
      repeat_interval: 5m
    - receiver: "null"
      matchers:
        - severity = "none"
        - alertname =~ "InfoInhibitor|Watchdog"
inhibit_rules:
  - equal: ["alertname", "namespace"]
    source_matchers:
      - severity = "error"
      - severity = "critical"
    target_matchers:
      - severity = "warning"

receivers:
- name: 'forward-to-primary-alertmanager'
  webhook_configs:
  - url: 'https://alertmanager.${ROOT_DOMAIN}/api/v2/alerts'
