---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./secret-store.yaml
  - ./crds/ks.yaml
  # - ./alertmanager/ks.yaml
  # - ./prometheus/ks.yaml
  # - ./loki/ks.yaml
  # - ./alloy/ks.yaml
  # - ./grafana/ks.yaml
  # - ./thanos/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./blackbox-exporter/ks.yaml
  - ./priority-class/ks.yaml
  - ./silences/ks.yaml
  - ./nut-exporter/ks.yaml
  - ./speedtest-exporter/ks.yaml
  - ./unpoller/ks.yaml
