---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-env
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        POSTGRES_HOST: "{{ .postgres_hostname }}"
        POSTGRES_PORT: "{{ .postgres_port }}"
        POSTGRES_DB: "{{ .postgres_database }}"
        POSTGRES_USER: "{{ .postgres_username }}"
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
        IGDB_CLIENT_ID: "{{ .twitch_username }}"
        IGDB_CLIENT_SECRET: "{{ .twitch_credential }}"
        JWT_SECRET: "{{ .questarr_jwt_secret }}"
        PROWLARR_URL: "prowlarr.flux-system.svc.cluster.local:9696"
  dataFrom:
    - extract:
        key: 'Twitch Developer'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "twitch_$1"
    - extract:
        key: 'questarr JWT Secret'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "questarr_$1"
    - extract:
        key: '${APP}-postgres'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgres_$1"

