---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pulumi
components:
  - ../../components/alerts
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./secrets/ks.yaml
  - ./applications/ks.yaml
  - ./authentik/ks.yaml
  - ./home-operations/ks.yaml
  - ./pulumi-operator/ks.yaml
