---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app homarr
  namespace: &namespace equestria
  labels:
    app.kubernetes.io/name: *app
    driscoll.dev/name: *app
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
      driscoll.dev/name: *app
  dependsOn:
    - name: volsync
      namespace: volsync-system
    - name: external-secrets
      namespace: kube-system
  path: ./kubernetes/apps/equestria/home/homarr
  prune: true
  wait: true
  interval: 1h
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/postgres
    - ../../../../components/tailscale
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
      PUID: "0"
      PGID: "0"
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_ACCESSMODES: ReadWriteMany
