---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: source-controller-allow-pulumi
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: source-controller
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: pulumi
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: flux-system
      ports:
        - protocol: TCP
          port: 80
