---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: GGRequestz
  category: Games
  description: Game request management system for Plex
  url: &url https://${APP}.${ROOT_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/plex.png
  access_policy:
    groups:
      - family
      - media-managers
  authentik:
    oauth2:
      clientType: confidential
      allowedRedirectUris:
        - url: "https://${APP}.${ROOT_DOMAIN}/api/auth/callback"
      propertyMappings:
        - email
        - openid
        - profile
        - ggrequestz_role
      includeClaimsInIdToken: true
      subMode: user_email
  gatus:
    - group: Applications
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
