---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-secrets
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        postgres_host: "{{ .postgres_hostname }}"
        postgres_database: "{{ .postgres_database }}"
        postgres_user: "{{ .postgres_username }}"
        postgres_password: "{{ .postgres_password }}"
        igdb_client_id: "{{ .igdb_client_id }}"
        igdb_client_secret: "{{ .igdb_client_secret }}"
        authentik_client_id: "{{ .oidc_client_id }}"
        authentik_client_secret: "{{ .oidc_client_secret }}"
        authentik_issuer: "{{ .oidc_issuer_url }}"
        session_secret: "{{ .session_secret }}"
  dataFrom:
    - extract:
        key: 'IGDB Credentials'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "igdb_$1"
    - extract:
        key: '${CLUSTER_CNAME}-${APP}-oidc-credentials'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "oidc_$1"
    - extract:
        key: '${APP}-postgres'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
    - extract:
        key: 'GGRequestz Secret'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "session_$1"
