---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-secrets
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        POSTGRES_HOST: "{{ .postgres_hostname }}"
        POSTGRES_PORT: "5432"
        POSTGRES_DB: "{{ .postgres_database }}"
        POSTGRES_USER: "{{ .postgres_username }}"
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
        IGDB_CLIENT_ID: "{{ .twitch_username }}"
        IGDB_CLIENT_SECRET: "{{ .twitch_credential }}"
        AUTHENTIK_CLIENT_ID: "{{ .oidc_client_id }}"
        AUTHENTIK_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        AUTHENTIK_ISSUER: "{{ .oidc_issuer }}"
        SESSION_SECRET: "{{ .session_credential }}"
        ROMM_SERVER_URL: "https://romm.${ROOT_DOMAIN}"
        ROMM_USERNAME: "{{ .romm_username }}"
        ROMM_PASSWORD: "{{ .romm_password }}"
  dataFrom:
    - extract:
        key: 'Twitch Developer'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "twitch_$1"
    - extract:
        key: '${CLUSTER_CNAME}-${APP}-oidc-credentials'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "oidc_$1"
    - extract:
        key: '${APP}-postgres'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
    - extract:
        key: 'ggrequestz Secret Key'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "session_$1"
    - extract:
        key: 'Romm'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "romm_$1"
