---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app grafana-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        GF_DATABASE_NAME: "{{ .postgres_database }}"
        GF_DATABASE_HOST: "{{ .postgres_hostname }}:{{ .postgres_port }}"
        GF_DATABASE_USER: "{{ .postgres_username }}"
        GF_DATABASE_PASSWORD: "{{ .postgres_password }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
        GF_AUTH_GENERIC_OAUTH_NAME: ${CLUSTER_TITLE} Grafana
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .oidc_client_id }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        GH_AUTH_GENERIC_OAUTH_AUTH_URL: "{{ .oidc_authorization_url }}"
        GH_AUTH_GENERIC_OAUTH_API_URL: "{{ .oidc_userinfo_url }}"
        GH_AUTH_GENERIC_OAUTH_TOKEN_URL: "{{ .oidc_token_url }}"
        GH_AUTH_GENERIC_OAUTH_AUTO_LOGIN: "true"
        GH_AUTH_GENERIC_OAUTH_LOGIN_PROMPT: "login"
        GH_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: "nickname"
        GH_AUTH_GENERIC_OAUTH_SCOPES: openid profile email grafana_role
        GH_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: "groups"
        GH_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_NAME: "email"
        GH_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "grafana_role"
  dataFrom:
    - extract:
        key: '${CLUSTER_CNAME}-${APP}-oidc-credentials'
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "oidc_$1"
    - extract:
        key: '${APP}-postgres'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app grafana-admin-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        # Admin User
        admin-user: "{{ .grafana_username }}"
        admin-password: "{{ .grafana_password }}"
  dataFrom:
    - extract:
        key: Grafana Credentials
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "grafana_$1"
