---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./definition.yaml
  - ./externalsecret.yaml
  - ./operator.yaml
  - ./datasources.yaml
  - ./dashboards/
generatorOptions:
  disableNameSuffixHash: true
