---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Tdarr
  category: Media Management
  url: https://${APP}.${ROOT_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/tdarr.svg
  access_policy:
    groups:
      - friends
      - family
  gatus:
    - group: "Applications"
      url: https://${APP}.${CLUSTER_DOMAIN}
      method: GET
      conditions:
        - "[STATUS] == 200"
