---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name tdarr
  namespace: &namespace equestria
  labels:
    app.kubernetes.io/name: *name
    driscoll.dev/name: *name
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
      driscoll.dev/name: *name
  dependsOn:
    - name: volsync
      namespace: volsync-system
  path: ./kubernetes/apps/equestria/media/tdarr
  prune: true
  wait: true
  force: false
  interval: 1h
  timeout: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/gateway/internal
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *name
      NAMESPACE: *namespace
