apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-user-push-secret.yaml
  - postgres-superuser-push-secret.yaml
  - crowdsec-postgres-push-secret.yaml
  - ggrequestz-postgres-push-secret.yaml
  - grafana-postgres-push-secret.yaml
  - homarr-postgres-push-secret.yaml
  - immich-postgres-push-secret.yaml
  - n8n-postgres-push-secret.yaml
  - pulsarr-postgres-push-secret.yaml
  - retrom-postgres-push-secret.yaml
  - romm-postgres-push-secret.yaml
  - tandoor-postgres-push-secret.yaml
  - vikunja-postgres-push-secret.yaml
  - windmill-postgres-push-secret.yaml