apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-user-push-secret.yaml
  - postgres-superuser-push-secret.yaml
  - grafana-postgres-push-secret.yaml
  - immich-postgres-push-secret.yaml
  - n8n-postgres-push-secret.yaml
  - romm-postgres-push-secret.yaml