---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Donetick
  category: Applications
  description: Done Tick is a task management tool
  url: &url https://tasks.${ROOT_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/donetick.svg
  access_policy:
    groups:
      - family
  authentik:
    oauth2:
      clientType: confidential
      allowedRedirectUris:
        - url: "https://tasks.${ROOT_DOMAIN}/auth/oauth2"
      propertyMappings:
        - email
        - openid
        - profile
        - entitlements
      includeClaimsInIdToken: true
      subMode: user_email
  gatus:
    - group: "Applications"
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
